### PR TITLE
refactor: mobile menu style

### PR DESCRIPTION
**Pull request by ruibaby**
1. 重构移动端的模态框菜单样式。
2. 修复移动端展开菜单按钮丢失的问题。

Fixes https://github.com/halo-dev/theme-earth/issues/28

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — COMMENTED** [review]
It works very well, but it doesn't seem to adapt to `night mode`.

image

**Comment by ruibaby** [comment]
> It works very well, but it doesn't seem to adapt to night mode.

已经支持。

image

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
