### PR TITLE
fix: Footer Style 2 Logo is not displayed properly

### PR DESCRIPTION
**Pull request by lan-yonghui**
What type of PR is this?

/kind bug

What this PR does / why we need it:

修复页脚风格二 Logo 显示不正确的问题。

Which issue(s) this PR fixes:
Fixes [halo-dev/halo#2894](https://github.com/halo-dev/halo/issues/2894)

Does this PR introduce a user-facing change?
```
none
```

### CODE REVIEW

**Comment by wan92hen** [comment]
这个在 #24 里改过了呀

**Comment by lan-yonghui** [comment]
> 这个在#24里改过了呀

没改完整，只修改了风格一的

**Review by ruibaby — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
